name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost-sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: BoostSecurity Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/native-scanner
          api_endpoint: https://api.dev.boostsec.io
      - name: Run Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4.0.2
        with:
          registry_module: boostsecurityio/bearer
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          api_endpoint: https://api.dev.boostsec.io
          log_level: DEBUG
          additional_args: --registry https://github.com/boostsecurityio/scanner-testing.git
